version: "3.8"
services:
  wait:
    build: dockerwait
    depends_on:
      - localstack

  app:
    build: .
    ports:
      - '8000:8000'
    environment:
      - ENDPOINT_URL=http://localstack:4566
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - QUEUE_URL=http://localstack:4566/000000000000/myqueue
      - LOG_LEVEL=DEBUG
    volumes:
      - ./s3/download:/download
      - ./s3/metadata:/metadata
    depends_on:
      wait:
        condition: service_completed_successfully

  localstack:
    image: localstack/localstack:latest
    ports:
      - '4566-4597:4566-4597'
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack-script.sh:/etc/localstack/init/ready.d/script.sh
      - ./notification.json:/etc/localstack/init/ready.d/notification.json
